# Generated by Django 5.2.17 on 2026-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('WHOLE', 'Butun gosht'), ('MEAT', 'Gosht'), ('FAT', 'Yog'), ('BONE', 'Suyak'), ('WASTE', 'Chiqit'), ('OTHER', 'Boshqa')], default='MEAT', max_length=20)),
                ('unit', models.CharField(choices=[('kg', 'kg')], default='kg', max_length=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
