# Generated by Django 5.2.17 on 2026-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WHOLE', 'Butun chorva'), ('BEEF', "Mol go'shti"), ('CHICKEN', "Tovuq go'shti"), ('LAMB', "Qo'y go'shti"), ('FAT', "Yog'"), ('BONE', 'Suyak'), ('WASTE', 'Chiqit'), ('OTHER', 'Boshqa')], default='BEEF', max_length=20),
        ),
    ]
