# Generated by Django 5.2.17 on 2026-09-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='pieces',
            field=models.PositiveIntegerField(default=0, help_text="Dona/bo'lak soni"),
        ),
    ]
