# Generated by Django 5.2.17 on 2026-09-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, help_text="To'lov qilinishi kerak bo'lgan muddat", null=True),
        ),
    ]
