# Generated by Django 5.2.17 on 2026-09-06 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0002_supplier_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Bu mijoz shu bilan birga yetkazib beruvchi ham.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='linked_supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_customer', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Boshlang'ich saldo (musbat = mijoz qarzdor).", max_digits=14),
        ),
    ]
