# Generated by Django 5.2.17 on 2026-09-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Boshlang'ich saldo (musbat = bizning qarzimiz).", max_digits=14),
        ),
    ]
