# Generated by Django 5.2.17 on 2026-09-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorycount_inventorycountitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="To'ldirilsa, ushbu mahsulot uchun tannarx shu qiymatga qayta belgilanadi (butun qoldiq chiqim qilinib, shu tannarx bilan qayta kirim qilinadi). Bo'sh qoldirilsa, tannarx o'zgarmaydi.", max_digits=14, null=True),
        ),
    ]
