# Generated by Django 5.2.17 on 2026-09-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_remove_purchase_legacy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='animal_type',
        ),
    ]
