# Generated by Django 5.2.17 on 2026-09-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_purchaseitem_animal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='gross_weight',
        ),
    ]
