# Generated by Django 5.2.17 on 2026-09-01 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Butchering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('output_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('yield_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('input_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='butchering_inputs', to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='butcherings', to='purchases.purchase')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ButcheringOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('butchering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='butchering.butchering')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='butchering_outputs', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
