# Generated by Django 5.2.17 on 2026-09-06 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchering', '0002_butcheringoutput_pieces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButcheringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('LABOR', 'Ishchi kuchi'), ('PACKAGING', 'Qadoqlash'), ('OTHER', 'Boshqa')], default='LABOR', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('butchering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_expenses', to='butchering.butchering')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
