# Generated by Django 5.2.17 on 2026-09-06 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchering', '0003_butcheringexpense'),
        ('products', '0007_finalize_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButcheringSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'ordering': ['parent_product__name', 'name'],
                'unique_together': {('parent_product', 'name')},
            },
        ),
        migrations.AddField(
            model_name='butchering',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butcherings', to='butchering.butcheringspecification'),
        ),
        migrations.CreateModel(
            name='ButcheringSpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('child_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_sources', to='products.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='butchering.butcheringspecification')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
