# Generated by Django 5.2.17 on 2026-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchering', '0004_butcheringspecification_butchering_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butchering',
            name='input_pieces',
            field=models.PositiveIntegerField(default=0, help_text="Bo'laklanayotgan dona/bo'lak soni"),
        ),
    ]
