# Generated by Django 5.2.17 on 2026-09-06 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchering', '0005_butchering_input_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcheringspecificationitem',
            name='cost_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Tannarxdan ulush %. Barcha qatorlar uchun to'ldirilsa, jami 100%% bo'lishi kerak. Bo'sh qoldirilsa, eskicha og'irlik (kg) ulushi bo'yicha taqsimlanadi.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
