# Generated by Django 5.2.17 on 2026-09-10 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butchering', '0006_butcheringspecificationitem_cost_percentage'),
        ('purchases', '0007_remove_purchaseitem_gross_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butchering',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='butcherings', to='purchases.purchase'),
        ),
    ]
